"""v0.6 5-schedule analysis types — frozen Explorer scoring_version=0.5.1."""
from __future__ import annotations

ANALYSIS_MACRO = "MACRO_HOLDINGS"
ANALYSIS_PREMARKET = "PREMARKET_CATALYSTS"
ANALYSIS_INTRADAY = "INTRADAY_OPPORTUNITY"
ANALYSIS_VALUE = "VALUE_QUALITY"
ANALYSIS_WEEKLY = "WEEKLY_XRAY"
ANALYSIS_EXPLORER = "EXPLORER"

ANALYSIS_TYPES = (
    ANALYSIS_MACRO,
    ANALYSIS_PREMARKET,
    ANALYSIS_INTRADAY,
    ANALYSIS_VALUE,
    ANALYSIS_WEEKLY,
)

JOB_ALIASES = {
    "all": list(ANALYSIS_TYPES),
    "macro": [ANALYSIS_MACRO],
    "premarket": [ANALYSIS_PREMARKET],
    "intraday": [ANALYSIS_INTRADAY],
    "value": [ANALYSIS_VALUE],
    "weekly": [ANALYSIS_WEEKLY],
}

MARKET_REGIME = {"RISK_ON", "NEUTRAL", "RISK_OFF", "MIXED", "NOT_RELIABLE"}
PORTFOLIO_POSTURE = {"NORMAL", "SELECTIVE", "DEFENSIVE", "NO_NEW_RISK", "NOT_RELIABLE"}
CATALYST_STATUS = {
    "POSITIVE_CONFIRMED", "POSITIVE_UNVERIFIED", "NEUTRAL",
    "NEGATIVE_CONFIRMED", "NEGATIVE_UNVERIFIED", "NO_MATERIAL_CATALYST_FOUND",
}
NEXT_SESSION_STATUS = {"PROMOTE", "KEEP", "DOWNGRADE", "REMOVE", "WATCH_ONLY"}
SETUP_STATE = {
    "NOT_STARTED", "EARLY_CONFIRMATION", "CONFIRMED", "PARTIAL_CONFIRMATION",
    "FAILED", "REJECTED_BREAKOUT", "RECLAIM", "OVEREXTENDED", "NO_TRADE", "NOT_RELIABLE",
}
FUNNEL_ACTION = {
    "NO_ACTION", "CONTINUE_FUNNEL", "START_FULL_FUNNEL", "RUN_DELTA", "REVIEW_EXISTING_FUNNEL",
}
FINAL_TACTICAL_STATUS = {
    "PRIORITY_WATCH", "WATCH", "WAIT_FOR_CONFIRMATION", "AVOID_CHASE", "NO_TRADE", "NOT_RELIABLE",
}
OUTCOME_STATUS = {"PENDING", "PARTIAL", "COMPLETE", "COMPLETE_FOR_5D", "NOT_EVALUABLE", "DATA_ERROR"}
CALIBRATION_STATUS = {"INSUFFICIENT_SAMPLE", "EARLY_SAMPLE", "DEVELOPING", "USABLE", "NOT_RELIABLE"}
USER_ACTIONS = {"NO_ACTION", "WATCHED", "BOUGHT", "SOLD", "ADDED", "TRIMMED", "OTHER"}
PRICE_BASIS = {"OFFICIAL_CLOSE", "CURRENT_INTRADAY_PRICE", "BAR_CLOSE", "PREVIOUS_CLOSE", "OTHER"}
SESSION_PHASES = {
    "PRE_OPEN", "CONTINUOUS_TRADING", "CLOSING_AUCTION", "TRADING_AT_LAST", "POST_CLOSE", "UNKNOWN",
}

SCORING_VERSION = "0.5.1"
LAYER_LOCAL_SIGNAL = "LOCAL_SIGNAL"
LAYER_CHATGPT_ANALYSIS = "CHATGPT_ANALYSIS"
LAYER_ACTUAL_OUTCOME = "ACTUAL_OUTCOME"
RESULT_ENVELOPE_VERSION = "1.1"
HANDOFF_SCHEMA_VERSION = "1.1"
SUPPORTED_RESULT_ENVELOPE_VERSION = RESULT_ENVELOPE_VERSION

LINKAGE_EXPLICIT = "EXPLICIT_CANONICAL_ID"
LINKAGE_FALLBACK = "FALLBACK_UNAMBIGUOUS"
LINKAGE_AMBIGUOUS = "AMBIGUOUS_REJECTED"
LINKAGE_INVALID = "INVALID_ID"
LINKAGE_NOT_LINKED = "NOT_LINKED"

PARSE_VALID = "VALID"
PARSE_INVALID_SCHEMA = "INVALID_SCHEMA"
PARSE_INVALID_CANONICAL_ID = "INVALID_CANONICAL_ID"
PARSE_TICKER_MISMATCH = "TICKER_CANONICAL_MISMATCH"
PARSE_AMBIGUOUS = "AMBIGUOUS_REJECTED"
PARSE_FALLBACK = "FALLBACK_UNAMBIGUOUS"
PARSE_NEEDS_REVIEW = "NEEDS_REVIEW"
PARSE_MISSING_ENVELOPE = "MISSING_ENVELOPE"

PHASE_MATCH = "MATCH"
PHASE_MISMATCH = "MISMATCH"
PHASE_MISSING = "MISSING"

WEEKLY_METRICS_SOURCE = "APP_GENERATED"
WEEKLY_INTERPRETATION_SOURCE = "CHATGPT_IMPORTED"

ANALYSIS_OBSERVATIONS_N_SEMANTICS = "DEPRECATED_ALIAS_OF_GENERATED"
DEPRECATED_FIELDS = ("analysis_observations_n",)

APP_OWNED_COUNT_FIELDS = (
    "scanner_sample_n",
    "canonical_signals_n",
    "analysis_observations_generated_n",
    "analysis_observations_imported_n",
    "analysis_observations_evaluable_n",
    "outcomes_complete_n",
    "outcomes_pending_n",
    "analysis_observations_n",
)

IDENTITY_FIELDS = (
    "ticker",
    "canonical_signal_id",
    "signal_family_id",
    "parent_signal_id",
    "market_state_fingerprint",
)

STALE_EVIDENCE_PHASES = {"POST_CLOSE", "PRE_OPEN"}
NOT_LIVE_CONFIRMATION_TEXT = "This is not live-session confirmation."

RESULT_SCHEMA_FILES = {
    ANALYSIS_MACRO: "macro_holdings_result_schema.json",
    ANALYSIS_PREMARKET: "premarket_catalysts_result_schema.json",
    ANALYSIS_INTRADAY: "intraday_opportunity_result_schema.json",
    ANALYSIS_VALUE: "value_quality_result_schema.json",
    ANALYSIS_WEEKLY: "weekly_xray_result_schema.json",
}

JOB_FILE = {
    ANALYSIS_MACRO: "macro_holdings.md",
    ANALYSIS_PREMARKET: "premarket_catalysts.md",
    ANALYSIS_INTRADAY: "intraday_opportunity.md",
    ANALYSIS_VALUE: "value_quality.md",
    ANALYSIS_WEEKLY: "weekly_xray.md",
}

JOB_ZIP_PREFIX = {
    ANALYSIS_MACRO: "EGX_MACRO_HOLDINGS",
    ANALYSIS_PREMARKET: "EGX_PREMARKET",
    ANALYSIS_INTRADAY: "EGX_INTRADAY",
    ANALYSIS_VALUE: "EGX_VALUE_QUALITY",
    ANALYSIS_WEEKLY: "EGX_WEEKLY_XRAY",
}
